version: "2"

services:
  indian-api:
    container_name: indian-api
    command: npm run start:prod
    env_file: ./config/env/.env.production
    build: .
    restart: always
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf.prod:/etc/nginx/conf.d/default.conf
      - ./nginx/cert.pem:/etc/cert.pem
      - ./nginx/key.pem:/etc/key.pem
