//Exception constants
export const OTP_EXPIRY_TIME = 5 * 60 * 1000;
export const OTP_TIME = 1440;

//AUTH
export const USER_UNAUTHORIZED_ERROR_CODE = 7;
export const INVALID_PASSWORD_AUTHENTIFICATION_ERROR_CODE = 5;
export const INVALID_OTP_AUTHENTIFICATION_ERROR_CODE = 6;
export const INVALID_REFRESH_AUTHENTIFICATION_ERROR_CODE = 51;
export const INVALID_ACCESS_AUTHENTIFICATION_ERROR_CODE = 52;
//INVITED CODE
export const INVITED_NOT_FOUND_ERROR_CODE = 53;
export const INVITED_OVERDUE_ERROR_CODE = 54;

//ACCOUNT
export const ACCOUNT_EXISTS_CLIENT_EXCEPTION_CODE = 41;
export const ACCOUNT_NOT_FOUND_EXCEPTION_CODE = 4;
export const CARD_NOT_FOUND_EXCEPTION_CODE = 9;
export const CARD_HAS_CLIENT_EXCEPTION_CODE = 10;
export const EMAIL_EXISTS_CLIENT_EXCEPTION_CODE = 42;
//OTP
export const OTP_INTERNAL_SERVER_ERROR_CODE = 3;


//ORDER
export const ORDER_PROCESSING_ERROR_CODE = 8;

export const BAY_IS_BUSY_ERROR_CODE = 81;
export const CARWASH_UNAVALIBLE_ERROR_CODE = 89;

//SERVER
export const SERVER_ERROR = 574;


